{
 "title": "Nomad Cluster",
 "description": "Nomad built-in telemetry https://github.com/dereknex/nomad-grafana",
 "tags": [
  "nomad",
  "instance",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": "label_values(nomad_client_uptime, datacenter)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_disk{datacenter=~\"$datacenter\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  { "title": "instance Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Uptime($instance)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_uptime{datacenter=~\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Idle($instance)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 22 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_idle{datacenter=\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 22 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "nomad_client_host_memory_used{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nomad_client_host_memory_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 22 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  {
   "title": "Disk Inodes ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_inodes_percent{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Uptime($instance)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_uptime{datacenter=~\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Idle($instance)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_idle{datacenter=\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "nomad_client_host_memory_used{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nomad_client_host_memory_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  {
   "title": "Disk Inodes ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_inodes_percent{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Uptime($instance)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_uptime{datacenter=~\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Idle($instance)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_idle{datacenter=\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "nomad_client_host_memory_used{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nomad_client_host_memory_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  {
   "title": "Disk Inodes ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_inodes_percent{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Uptime($instance)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_uptime{datacenter=~\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Idle($instance)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_idle{datacenter=\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "nomad_client_host_memory_used{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nomad_client_host_memory_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  {
   "title": "Disk Inodes ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_inodes_percent{datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}