{
 "title": "Speedtest Dashboard",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ping and Jitter (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Jitter (ms)"
    }
   ]
  },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Mbits", "label": "Download Speed" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second*10^-6",
     "legendFormat": "Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Mbits", "label": "Upload Speed" }
   ],
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second*10^-6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  }
 ]
}