global:
  name: consul
  datacenter: dc2
  image: 'hashicorp/consul-enterprise:1.11.1-ent'
  enterpriseLicense:
    secretName: 'consul-license'
    secretKey: 'key'
  tls:
    enabled: true
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey
  federation:
    enabled: true
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
server:
  extraConfig: |
    {
      "log_level": "DEBUG",
      "primary_datacenter": "dc1",
      "primary_gateways": ["mesh-gateway.service.consul:9100"]
    }
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
ui:
  enabled: true
connectInject:
  enabled: true
  envoyExtraArgs: "--component-log-level upstream:debug,http:debug,router:debug,config:debug"
controller:
  enabled: true
  replicas: 1
meshGateway:
  enabled: true
  replicas: 1
ingressGateways:
  enabled: true
  replicas: 1
  defaults:
    service:
      type: NodePort
      ports:
        - port: 30080
          nodePort: 30080
  gateways:
    - name: dc2-ingress-gateway